"""Business logic for user registration and login authentication.

Kept separate from the router so app/routers/auth.py only deals with
HTTP concerns (status codes, request/response schemas) while this module
owns the MongoDB access and business rules.
"""

import re
from datetime import datetime, timezone
from typing import Optional

from bson import ObjectId
from pymongo import ReturnDocument
from pymongo.errors import DuplicateKeyError

from app.core.security import hash_password, verify_password
from app.database import get_database
from app.models.user import UserModel, UserType
from app.schemas.user import UserRegister, UserUpdateByAdmin, UserUpdateSelf

USERS_COLLECTION = "users"


class EmailAlreadyExistsError(Exception):
    """Raised by register_user / update_own_profile when the email is
    already taken by another account.

    The router catches this and returns 409 Conflict.
    """


class InvalidCredentialsError(Exception):
    """Raised by authenticate_user for any login failure: unknown email,
    wrong password, or a soft-deleted account.

    Deliberately a single exception (and message) for all three cases, so
    the router's response can't be used to probe whether a given email is
    registered.
    """


class UserNotFoundError(Exception):
    """Raised when an operation targets a user id that no longer exists.

    Not expected in normal use — get_current_user already confirmed the
    caller's account exists earlier in the same request — but guards against
    the (rare) race where the account is deleted mid-request.
    """


async def register_user(user_data: UserRegister) -> UserModel:
    """Create a new client account from a public registration payload.

    Always creates the user with type=CLIENT — UserRegister has no `type`
    field to begin with, but this is the explicit enforcement point in case
    that schema is ever changed.
    """
    collection = get_database()[USERS_COLLECTION]

    if await collection.find_one({"email": user_data.email}):
        raise EmailAlreadyExistsError(f"Email '{user_data.email}' is already registered")

    now = datetime.now(timezone.utc)
    user = UserModel(
        first_name=user_data.first_name,
        last_name=user_data.last_name,
        email=user_data.email,
        phone=user_data.phone,
        city=user_data.city,
        age=user_data.age,
        type=UserType.CLIENT,
        hashed_password=hash_password(user_data.password),
        is_deleted=False,
        created_at=now,
        updated_at=now,
    )

    # `user.id` was already generated by UserModel's default_factory, so the
    # dumped doc already carries the `_id` MongoDB will store it under.
    try:
        await collection.insert_one(user.model_dump(by_alias=True))
    except DuplicateKeyError as exc:
        # Belt-and-braces: the find_one check above isn't atomic with this
        # insert, so a concurrent registration for the same email could slip
        # past it. The unique index on `email` (see connect_to_mongo) is the
        # real guard; this turns its rejection into the same clean 409 the
        # router already expects, instead of an unhandled 500.
        raise EmailAlreadyExistsError(f"Email '{user_data.email}' is already registered") from exc

    return user


async def authenticate_user(email: str, password: str) -> UserModel:
    """Verify login credentials and return the matching user.

    Raises InvalidCredentialsError for any failure so the caller (the /login
    route) can respond with one generic "incorrect email or password"
    message regardless of which check actually failed.
    """
    user_doc = await get_database()[USERS_COLLECTION].find_one({"email": email})
    if user_doc is None:
        raise InvalidCredentialsError("Incorrect email or password")

    user = UserModel(**user_doc)

    if user.is_deleted:
        raise InvalidCredentialsError("Incorrect email or password")

    if not verify_password(password, user.hashed_password):
        raise InvalidCredentialsError("Incorrect email or password")

    return user


async def update_own_profile(user_id: str, update_data: UserUpdateSelf) -> UserModel:
    """Apply a partial self-service profile update.

    Only fields actually present in the request (`exclude_unset=True`) are
    changed — omitted fields are left untouched, not overwritten with None.
    Changing email is blocked if another user already has it; changing
    password hashes it before storage. UserUpdateSelf has no `type` field,
    so this function has no way to touch a user's role even in principle.
    """
    collection = get_database()[USERS_COLLECTION]
    fields = update_data.model_dump(exclude_unset=True)

    if "email" in fields:
        conflict = await collection.find_one(
            {"email": fields["email"], "_id": {"$ne": ObjectId(user_id)}}
        )
        if conflict:
            raise EmailAlreadyExistsError(f"Email '{fields['email']}' is already registered")

    if "password" in fields:
        fields["hashed_password"] = hash_password(fields.pop("password"))

    if not fields:
        # Nothing to change — just return the current state, no write needed.
        current_doc = await collection.find_one({"_id": ObjectId(user_id)})
        if current_doc is None:
            raise UserNotFoundError(f"User '{user_id}' not found")
        return UserModel(**current_doc)

    fields["updated_at"] = datetime.now(timezone.utc)

    try:
        updated_doc = await collection.find_one_and_update(
            {"_id": ObjectId(user_id)},
            {"$set": fields},
            return_document=ReturnDocument.AFTER,
        )
    except DuplicateKeyError as exc:
        # Same race-condition backstop as register_user: the find_one check
        # above isn't atomic with this update. `email` is the only unique
        # index, so if it's absent this update couldn't have changed it and
        # this branch shouldn't be reachable — fall back to a generic
        # message rather than risk a KeyError inside an exception handler.
        email = fields.get("email", "<unknown>")
        raise EmailAlreadyExistsError(f"Email '{email}' is already registered") from exc

    if updated_doc is None:
        raise UserNotFoundError(f"User '{user_id}' not found")

    return UserModel(**updated_doc)


async def update_user_by_admin(user_id: str, update_data: UserUpdateByAdmin) -> UserModel:
    """Apply a partial admin-driven update to any user, by id.

    Unlike update_own_profile, UserUpdateByAdmin includes `type`, so this is
    the one place a role change is allowed to happen. Soft-deleted users are
    treated as not found (raises UserNotFoundError, same as a nonexistent
    id) — reviving a deleted account isn't this endpoint's job. Email
    changes are checked for uniqueness against other users, same as
    update_own_profile.
    """
    if not ObjectId.is_valid(user_id):
        raise UserNotFoundError(f"User '{user_id}' not found")

    collection = get_database()[USERS_COLLECTION]
    fields = update_data.model_dump(exclude_unset=True)

    if "email" in fields:
        conflict = await collection.find_one(
            {"email": fields["email"], "_id": {"$ne": ObjectId(user_id)}}
        )
        if conflict:
            raise EmailAlreadyExistsError(f"Email '{fields['email']}' is already registered")

    query = {"_id": ObjectId(user_id), "is_deleted": False}

    if not fields:
        # Nothing to change — just return the current state, no write needed.
        current_doc = await collection.find_one(query)
        if current_doc is None:
            raise UserNotFoundError(f"User '{user_id}' not found")
        return UserModel(**current_doc)

    fields["updated_at"] = datetime.now(timezone.utc)

    try:
        updated_doc = await collection.find_one_and_update(
            query,
            {"$set": fields},
            return_document=ReturnDocument.AFTER,
        )
    except DuplicateKeyError as exc:
        # Same race-condition backstop as register_user/update_own_profile.
        email = fields.get("email", "<unknown>")
        raise EmailAlreadyExistsError(f"Email '{email}' is already registered") from exc

    if updated_doc is None:
        raise UserNotFoundError(f"User '{user_id}' not found")

    return UserModel(**updated_doc)


async def soft_delete_user(user_id: str) -> None:
    """Soft-delete a user by id: sets is_deleted=True + deleted_at/updated_at,
    the document is never actually removed from MongoDB.

    Matches only currently-active users (`is_deleted: False`), so an already
    soft-deleted id — like a nonexistent one — matches zero documents and
    raises UserNotFoundError. That keeps this from being callable twice on
    the same user (each call past the first is a genuine 404, not a silent
    no-op success), and re-uses the same is_deleted filter already applied
    by get_users/authenticate_user/get_current_user.
    """
    if not ObjectId.is_valid(user_id):
        raise UserNotFoundError(f"User '{user_id}' not found")

    now = datetime.now(timezone.utc)
    result = await get_database()[USERS_COLLECTION].update_one(
        {"_id": ObjectId(user_id), "is_deleted": False},
        {"$set": {"is_deleted": True, "deleted_at": now, "updated_at": now}},
    )
    if result.matched_count == 0:
        raise UserNotFoundError(f"User '{user_id}' not found")


async def get_users(page: int, limit: int, filters: dict) -> tuple[list[UserModel], int]:
    """Fetch one page of non-deleted users, optionally narrowed by filters.

    `filters` may contain any of: city, type, first_name, last_name, email
    (all optional — omitted/None/empty values are ignored, so filters are
    freely combinable). The string filters are matched as case-insensitive
    partial matches (regex `.search` semantics), which behaves like a search
    box rather than requiring an exact value; `type` is matched exactly
    since it's an enum, not free text. Returns (page_of_users, total_count)
    so the router can compute total_pages without a second query.
    """
    collection = get_database()[USERS_COLLECTION]

    query: dict = {"is_deleted": False}

    for field in ("city", "first_name", "last_name", "email"):
        value = filters.get(field)
        if value:
            # re.escape so a filter value containing regex metacharacters
            # (e.g. "a+b") is treated as a literal substring, not a pattern.
            query[field] = {"$regex": re.escape(value), "$options": "i"}

    user_type: Optional[UserType] = filters.get("type")
    if user_type:
        query["type"] = user_type.value if isinstance(user_type, UserType) else user_type

    total = await collection.count_documents(query)

    skip = (page - 1) * limit
    cursor = collection.find(query).skip(skip).limit(limit)
    users = [UserModel(**doc) async for doc in cursor]

    return users, total


# --- Public aggregate stats -------------------------------------------------
# Same `is_deleted: False` scoping as get_users/authenticate_user/
# get_current_user, so soft-deleted users never show up in these figures
# even though the /stats endpoints themselves are unauthenticated.


async def get_active_user_count() -> int:
    """Total number of active (non-deleted) users."""
    return await get_database()[USERS_COLLECTION].count_documents({"is_deleted": False})


async def get_average_age() -> tuple[Optional[float], int]:
    """Average `age` across active users, plus how many users that covers.

    UserModel only has a required `age: int` field (no date-of-birth), so
    age is used as-is rather than derived from a birth date. Returns
    (None, 0) when there are no active users, so the router can represent
    "no data" instead of a misleading average of 0.
    """
    pipeline = [
        {"$match": {"is_deleted": False}},
        {"$group": {"_id": None, "average_age": {"$avg": "$age"}, "count": {"$sum": 1}}},
    ]
    result = await get_database()[USERS_COLLECTION].aggregate(pipeline).to_list(length=1)
    if not result:
        return None, 0

    return round(result[0]["average_age"], 2), result[0]["count"]


async def get_top_cities(limit: int = 5) -> list[dict]:
    """Top `limit` cities by active-user count, descending."""
    pipeline = [
        {"$match": {"is_deleted": False}},
        {"$group": {"_id": "$city", "count": {"$sum": 1}}},
        {"$sort": {"count": -1}},
        {"$limit": limit},
    ]
    results = await get_database()[USERS_COLLECTION].aggregate(pipeline).to_list(length=limit)
    return [{"city": doc["_id"], "count": doc["count"]} for doc in results]
