"""Business logic for user registration and login authentication.

Kept separate from the router so app/routers/auth.py only deals with
HTTP concerns (status codes, request/response schemas) while this module
owns the MongoDB access and business rules.
"""

from datetime import datetime, timezone

from app.core.security import hash_password, verify_password
from app.database import get_database
from app.models.user import UserModel, UserType
from app.schemas.user import UserRegister

USERS_COLLECTION = "users"


class EmailAlreadyExistsError(Exception):
    """Raised by register_user when the email is already taken.

    The router catches this and returns 409 Conflict.
    """


class InvalidCredentialsError(Exception):
    """Raised by authenticate_user for any login failure: unknown email,
    wrong password, or a soft-deleted account.

    Deliberately a single exception (and message) for all three cases, so
    the router's response can't be used to probe whether a given email is
    registered.
    """


async def register_user(user_data: UserRegister) -> UserModel:
    """Create a new client account from a public registration payload.

    Always creates the user with type=CLIENT — UserRegister has no `type`
    field to begin with, but this is the explicit enforcement point in case
    that schema is ever changed.
    """
    collection = get_database()[USERS_COLLECTION]

    if await collection.find_one({"email": user_data.email}):
        raise EmailAlreadyExistsError(f"Email '{user_data.email}' is already registered")

    now = datetime.now(timezone.utc)
    user = UserModel(
        first_name=user_data.first_name,
        last_name=user_data.last_name,
        email=user_data.email,
        phone=user_data.phone,
        city=user_data.city,
        age=user_data.age,
        type=UserType.CLIENT,
        hashed_password=hash_password(user_data.password),
        is_deleted=False,
        created_at=now,
        updated_at=now,
    )

    # `user.id` was already generated by UserModel's default_factory, so the
    # dumped doc already carries the `_id` MongoDB will store it under.
    await collection.insert_one(user.model_dump(by_alias=True))
    return user


async def authenticate_user(email: str, password: str) -> UserModel:
    """Verify login credentials and return the matching user.

    Raises InvalidCredentialsError for any failure so the caller (the /login
    route) can respond with one generic "incorrect email or password"
    message regardless of which check actually failed.
    """
    user_doc = await get_database()[USERS_COLLECTION].find_one({"email": email})
    if user_doc is None:
        raise InvalidCredentialsError("Incorrect email or password")

    user = UserModel(**user_doc)

    if user.is_deleted:
        raise InvalidCredentialsError("Incorrect email or password")

    if not verify_password(password, user.hashed_password):
        raise InvalidCredentialsError("Incorrect email or password")

    return user
